### ISSUE TITLE
Reasses the interfaces

### ISSUE THREAD

**Issue by dvberkel** [phedny/Mammon#11]
In the refactoring done in pull request [#10](https://github.com/phedny/Mammon/pull/10) a lot of group elements turned into BigIntegers. as a consequence the return type of [Coin#getCoinSignature](https://github.com/phedny/Mammon/blob/master/interfaces/src/main/java/org/mammon/brands/Coin.java#L40) changed from `Group.Element<G>[]` to `Object[]`.

Maybe because the interfaces can be cleaned up to reflect the change in insight.

**Comment by phedny** [comment]
Interface FiniteField<F> has been introduced. Changing the coin signature will be part of [issue #12](https://github.com/phedny/Mammon/issues/12)
