### ISSUE TITLE
Generating a primitive root is unusably slow

### ISSUE THREAD

**Issue by phedny** [phedny/Mammon#16]
When generating a root for large primes, it takes ages to find a root (as part of GqSetupFactory.createGenerator()). For primes that are of secure size, it's unusable and therefore this issue is marked as a bug.

**Comment by dvberkel** [comment]
The `GqSetupFactory` was created with the intention of generating a `GqSetup` once after we decided on the group parameters. From then on we can us the `GqSetup` to recreate the group.

In light of the preceding comment is this still an issue?

**Comment by phedny** [comment]
Acknowledged.
