### ISSUE TITLE
Start using Travis CI

### ISSUE THREAD

**Issue by dvberkel** [phedny/Mammon#17]
[Travis CI](http://travis-ci.org/) is 

> a hosted continuous integration service for the open source community.

Commit 96408b2a24f24f58db0f500dac5e28a1a1b46e37 introduces a basic `.travis.yml`. Currently this will sit there idle until the project is registered on Travis CI. (As detailed by the [documentation](http://about.travis-ci.org/docs/user/getting-started/).)

@phedny  : you should make these steps because you have to authenticate with your GitHub Account on Travis CI.

**Comment by phedny** [comment]
The [Travis CI](http://travis-ci.org/) website doesn't really work for me. The site looks weird and I cannot scroll or click any links. After a while, Chrome reports about a runaway JavaScript. Are you having the same issues or is something wrong on my side?

**Comment by dvberkel** [comment]
O checked on a tablet with chrome and it does not responsive very well. I use firebox on injury with no problems

**Comment by dvberkel** [comment]
This [tweet](https://twitter.com/#!/travisci/status/192745142367686657) probably explains our difficulties with the website. They [claim](https://twitter.com/#!/travisci/status/192794491000860673) to be back on track do.

Try again.

**Comment by dvberkel** [comment]
The Mammon is project is building on Travis So I am closing this issue
