### ISSUE TITLE
Group.Element Interface wrong

### ISSUE THREAD

**Issue by dvberkel** [phedny/Mammon#8]
The [Element](https://github.com/phedny/Mammon/blob/master/interfaces/src/main/java/org/mammon/brands/Group.java#L34) has two methods for which the intended purpose is unclear.
- [Multiply](https://github.com/phedny/Mammon/blob/master/interfaces/src/main/java/org/mammon/brands/Group.java#L58)
- [Exponentiate](https://github.com/phedny/Mammon/blob/master/interfaces/src/main/java/org/mammon/brands/Group.java#L65)

What is the purpose of these methods?

**Comment by phedny** [comment]
The intended purpose is to implement multiplication and exponentiation in a group like \mathbb{Z}_p^*

Maybe I don't really understand what's unclear to you.

**Comment by dvberkel** [comment]
A mathematical group only supports one operation. For commutative groups it is custom to use addition for general groups multiplication. Mixing the two would obscure (for me) the intended use.

It seems that the interface leaks a possible implementation i.e. \mathbb{Z}_p or \mathbb{Z}_p^*. But it is possible to create groups other groups e.g. Free groups modulo generators. In this setting it is not natural to talk about both adding and multiplying, let along exponentiation.

We could proceed in to ways:
1. We could choose to restrict the interface to match the contract \mathbb{Z}_p^*
2. Leave open what kind of group to use and figure out how we are using the groups.

**Comment by phedny** [comment]
From the Brands paper:

"All arithmetic in this article is performed in a group $G_q$ of prime order $q$ for which polynomial-time algorithms are known to multiply, invert, determine equality of elements, test membership, and randomly select elements. There is a vast variety of groups known to satisfy these requirements."

...

"Although our electronic cash system can be implemented with any group $G_q$ that satisfies the listed conditions, and for which no feasible algorithms are known to compute discrete logarithms, we will for explicitness assume henceforth that $G_q$ is the unique subgroup of order $q$ of some multiplicative group \mathbb{Z}_p^*, for a prime $p$ such that $q | (p - 1}$."

So, if you prefer, we can rename the too general "Group" interface to "CompatibleGroup" to indicate there are some more restrictions compared to a regular mathematical group. \mathbb{Z}_p^\* and \mathbb{Z}_p can be implementations.

**Comment by dvberkel** [comment]
I will read the paper again to see how Brands (mis)uses the above mentioned group. It could be possible that he use more properties of \mathbb{Z}_p^\* which we need.

I will update the interface accordingly.

**Comment by dvberkel** [comment]
I have reread Brands paper and can understand where the confusion comes from. There are two related but dissimilar structures used in the paper.
1. _G_q_ a subgroup of \mathbb{Z}_p^\* of prime order
2. _\mathbb{Z}_q_ the field of integers modulo q.

Although the seem related they are distinct. For example we could not use \mathbb{Z}_p as our group G_q because the descrete logarithm problem would be trivial.

To make a long story short. I will change the interface accordingly. Should we introduce another interface for the field of integers modulo q, or do we rely on BigDecimals?

**Comment by phedny** [comment]
Fixed by introducing FiniteField<F>, which exists next to Group<F>.
